include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_const_literals_to_create_immutables: true
    avoid_redundant_argument_values: true
    avoid_empty_else: true
    prefer_typing_uninitialized_variables: true
    avoid_returning_null_for_future: true
    sort_child_properties_last: true
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    avoid_unnecessary_containers: true
    avoid_function_literals_in_foreach_calls: true
    prefer_is_not_empty: true
    prefer_collection_literals: true
    unnecessary_const: true
    prefer_inlined_adds: true
    use_raw_strings: true
    prefer_final_in_for_each: true
    prefer_const_declarations: true